### ISSUE TITLE
[Bug]: `PageIterator` skip last track

### ISSUE THREAD

**Issue by LWJerri** [MellKam/soundify#47]
For example, I have a playlist with 45 tracks, and when I use PageIterator for getPlaylistTracks I receive a partial tracks list. Here minimal code to reproduce the problem:

```ts
const playlistTracksIterator = new PageIterator((opts) =>
  getPlaylistTracks(client, PLAYLIST_ID, opts),
);
const playlistTracksList = await playlistTracksIterator.collect();

console.log(preparedTracksList.length); // 44, because last track is missed.
```

**Comment by LWJerri** [comment]
@MellKam, bug isn't fixed.

**Comment by MellKam** [comment]
@LWJerri Make sure you updated to the last version. That's really strange cause I even wrote a test for it and it all works. Can you reproduce it with other playlist or it is just with this one? I even tried it with some random spotify playlist and it works. 

Also a small tip. You can provide a maximum limit for endpoint you trying to reach, so you make less request overall.  
```ts
const playlistTracksIterator = new PageIterator((opts) =>
  getPlaylistTracks(client, PLAYLIST_ID, opts),
  { limit: 50 } // 50 is max limit for this endpoint
);
```

**Comment by LWJerri** [comment]
Yeap, I have latest package version, let me try another playlists.

**Comment by LWJerri** [comment]
I tried this code on a playlist from spotify with exactly 100 tracks and ended up with 98 tracks after .collect(). I also set the maximum limit per request to 50 tracks, it looks like the 2 missing tracks are the result of two 50 track requests.

![image](https://github.com/MellKam/soundify/assets/50290430/95debe4b-e8a5-4718-9293-e6ef17d66130)
![image](https://github.com/MellKam/soundify/assets/50290430/ee68751a-83ec-4217-a239-6752916f5f63)

**Comment by LWJerri** [comment]
OOOPSSS, my bad

**Comment by LWJerri** [comment]
Okay, now I have package `v1.0.0-rc11` and still have only 99 songs instead of 100. Here my code:
```ts
const playlistTracksIterator = new PageIterator(
  (opts) => getPlaylistTracks(this.client, env.SPOTIFY_PLAYLIST_ID, opts),
  { limit: 50 },
);

const playlistTracksList = await playlistTracksIterator.collect();

console.log(playlistTracksList.length);
```

**Comment by MellKam** [comment]
Just tried to test it with my 2023 wrapped playlist and it passed

```ts
Deno.test("PageIterator: real playlist", async () => {
	const pageIterator = new PageIterator(
		(opts) => getPlaylistTracks(client, "37i9dQZF1Fa1IIVtEpGUcU", opts),
		{ limit: 50 },
	);

	const items = await pageIterator.collect();
	assertEquals(items.length, 100);
});
```

**Comment by LWJerri** [comment]
> Just tried to test it with my 2023 wrapped playlist and it passed
> 
> ```ts
> Deno.test("PageIterator: real playlist", async () => {
> 	const pageIterator = new PageIterator(
> 		(opts) => getPlaylistTracks(client, "37i9dQZF1Fa1IIVtEpGUcU", opts),
> 		{ limit: 50 },
> 	);
> 
> 	const items = await pageIterator.collect();
> 	assertEquals(items.length, 100);
> });
> ```

Well, can you join my stream to show you in live what happens?

twitch.tv/LWGerry

**Comment by LWJerri** [comment]
:shipit:, bc solved.
